version: 1
labels:
- label: "automerge"
  authors: ["scala-steward", "github-actions[bot]", "app/renovate"]
- label: "auto-approve"
  authors: ["scala-steward", "github-actions[bot]", "app/renovate"]
