name: Auto approve

on:
  pull_request_target: {}

jobs:
  auto-approve:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        if: contains(github.event.pull_request.labels.*.name, 'auto-approve')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
